### ISSUE TITLE
Error when stopping device

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-HTTPd#6]
````
Jan 24, 2020 at 1:24:18 PM
   HTTPd 2                         http 5555: Stopping serverDevice Device 607244738
   HTTPd 2 Error                   Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 322, in runConcurrentThread
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 274, in handle_request
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
error: (9, 'Bad file descriptor')

   HTTPd 2 Error                   plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   HTTPd 2                         http 5555: Starting serverDevice Device 607244738
   HTTPd 2 Debug                   Started HTTP server on port 5555
   HTTPd 2 Debug                   MyHTTPServer, username = username, password = password, digest = True
   HTTPd 2 Debug                   MyHTTPServer, devID = 607244738
````

**Comment by FlyingDiver** [comment]
Fixed in https://github.com/FlyingDiver/Indigo-HTTPd-2/releases/tag/2.0.1
