### ISSUE TITLE
Errors creating Proxy device

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-HTTPd#7]
```
HTTPd                           dbell: Starting proxyDevice Device 1518360974
HTTPd Error                     Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7.4/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1179, in deviceUpdated
  File "plugin.py", line 395, in deviceStartComm
AttributeError: 'NoneType' object has no attribute 'get'
```

More:  https://forums.indigodomo.com/viewtopic.php?f=216&t=17281&p=187895#p187889

**Comment by FlyingDiver** [comment]
Will not fix.  Migrate to the V2 plugin.
